### ISSUE TITLE
Blocks video

### ISSUE THREAD

**Issue by M1Aston** [CodyMcCodington/AutoCookieOptout#20] opened 2021-11-22 18:10 UTC
**Describe the bug**
Blocks video playback on several newspaper websites (I think all part of the same company, so the same problem?).

**Reproduction steps**
Two examples:
https://www.destentor.nl/video/
https://www.ad.nl/video

**Expected behavior**
Play video

**Screenshots**

- Auto Cookie Optout version:
- 0.7

**Comment by M1Aston** [comment] 2021-11-22 18:14
One more things.
Doesn't work on the website of the biggest Dutch newspaper
https://www.telegraaf.nl/

**Comment by CodyMcCodington** [comment] 2021-12-05 19:03
Hi M1Aston. I went to https://www.destentor.nl/video/ and https://www.ad.nl/video, on both of which video was playing normally for me with ACO v0.7. To ensure it's an ACO issue, could you try playing the videos with all your other extensions disabled?

As for https://www.telegraaf.nl/, it works for me, but not consistently. Sometimes the optout only works after I manually refresh the page, so I'm gonna have to investigate that one.

**Comment by M1Aston** [comment] 2021-12-05 20:29
Yes, they seem to be working OK now. I don't really know what happened before.

**Comment by CodyMcCodington** [comment] 2021-12-05 20:34
And suddenly I can't reproduce the issue on https://www.telegraaf.nl/ either despite 5 tries 🤔 Closing for now but keeping an eye out for this.

**Closed by CodyMcCodington** 2021-12-05 20:34 UTC

**Comment by M1Aston** [comment] 2021-12-05 20:54
Well, telegraaf videos still don't load here when enabled AND there was no cookie set yet. After disabling the extension the cookie menu pops up and after (manually) allowing a cookie to be set everything works. Even after enabling the extension other videos will load properly as well (which makes sense, because the cookie is still there).

No cookie + extension enabled = no-go for videos.

**Comment by CodyMcCodington** [comment] 2021-12-06 08:24
Ahh okay, I think I figured it out. So I went to https://www.telegraaf.nl/video/ with ACO v0.7 in a private tab and indeed, there's a just a black rectangle where the video is supposed to play. This is a consequence of ACO opting you out to all cookies, including social media cookies. When I scroll down to the bottom, click Cookies, and set social media cookies to allowed, the video starts playing even with ACO enabled.

So as far as I can tell, this is a logical consequence of Telegraph's use of social media cookies in their video player. If you clear all Telegraph cookies, enable ACO, go to their site, scroll down, click Cookies, enable social media cookies and try to play the video, does it work for you as well?

**Comment by M1Aston** [comment] 2021-12-06 18:04
Cookies can be personalized here. There are 7 components (including social media). 

Each time, starting with no cookies set, I have tested 3 of these options (allowing 1 and blocking 6 others). In all cases, video loading worked normally after that, even with "social media" blocked and allowing some other option. It seems in order for videos to work, they need a cookie to be set, no matter what it contains.

Anyway, it is what it is.  Thanks for looking into this. Just don't spend too much time on it. :-D
